const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..", "..");
const outputPath = path.join(root, "app", "public", "assets", "app.bundle.js");

const modules = {
  scheduler: path.join(root, "node_modules", "scheduler", "cjs", "scheduler.development.js"),
  react: path.join(root, "node_modules", "react", "cjs", "react.development.js"),
  "react-dom": path.join(root, "node_modules", "react-dom", "cjs", "react-dom.development.js"),
  "react-dom/client": path.join(root, "node_modules", "react-dom", "cjs", "react-dom-client.development.js"),
  app: path.join(root, "app", "src", "main.js"),
};

function readModule(filePath) {
  return fs.readFileSync(filePath, "utf8");
}

function factory(id, filePath) {
  const source = readModule(filePath);
  return `modules[${JSON.stringify(id)}] = function(require, module, exports, process) {\n${source}\n};\n`;
}

const bundle = `/* Generated by app/scripts/build-react.js. Do not edit directly. */
(function () {
  const modules = {};
  const cache = {};
  const process = { env: { NODE_ENV: "development" } };

${Object.entries(modules)
  .map(([id, filePath]) => factory(id, filePath))
  .join("\n")}

  function require(id) {
    if (cache[id]) return cache[id].exports;
    if (!modules[id]) throw new Error("Module not found: " + id);
    const module = { exports: {} };
    cache[id] = module;
    modules[id](require, module, module.exports, process);
    return module.exports;
  }

  require("app");
})();
`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, bundle, "utf8");
console.log(`Built ${path.relative(root, outputPath)}`);
